timeline
    title History of Twitter
    2006: Twitter Founded
    2007: Twitter becomes its own company
    2009: Twitter introduces trending topics
    2010: Twitter introduces the "Promoted Tweets" advertising model
    2013: Twitter goes public with its IPO
    2016: Twitter launches live video streaming feature
